### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by PokemonGoF-IssueMover** [PokemonGoF/PokemonGo-Bot-Issues#3]
_From @TheSavior on August 4, 2016 18:4_

Looks like when the bot is starting up, these fields aren't populated so we get `None` back. We should return 0 if either of these are None

https://app.getsentry.com/pokemongof/pokemongo-bot/issues/147416492/

```
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
  File "pokecli.py", line 490, in <module>
    main()
  File "pokecli.py", line 95, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    logger.info('Total XP Earned: {}  Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()))
  File "pokemongo_bot/metrics.py", line 28, in xp_earned
    return self.xp['latest'] - self.xp['start']

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

_Copied from original issue: PokemonGoF/PokemonGo-Bot#2596_

**Comment by PokemonGoF-IssueMover** [comment]
_From @fence1247 on August 7, 2016 16:23_

I am having this issue. How to we alter the pokecly.py files so that I no longer get this error?

016-08-07 10:19:24,084 [PokemonGoBot] [INFO] 
2016-08-07 10:19:24,084 [PokemonGoBot] [INFO] 
2016-08-07 10:19:31,577 [       cli] [INFO] 
2016-08-07 10:19:31,577 [       cli] [INFO] Ran for 0:00:11
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    logger.info('Total XP Earned: {}  Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()))
  File "/Users/trevor/PokemonGo-Bot/pokemongo_bot/metrics.py", line 28, in xp_earned
    return self.xp['latest'] - self.xp['start']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by PokemonGoF-IssueMover** [comment]
_From @TheSavior on August 7, 2016 17:56_

This is still a problem.
